### ISSUE TITLE
Document progress workflow

### ISSUE THREAD

**Issue by jayoshih** [learningequality/studio-docs#6]
## Summary

The following workflows are now slightly different due to the inclusion of progress bars:

- [ ] Publishing
- [ ] Moving content using the move option
- [ ] Copying content (Make a copy, copy to clipboard)
- [ ] Importing content

**Comment by radinamatic** [comment]
@jayoshih I'm trying to arrive to the progress bar when moving items with the **Move** tool in the toolbar, but I can't seem to get any user-facing notification, much less a progress bar. No errors in the Network/Console, but the results are only visible when the page is refreshed. Am I missing something?

![2019-08-20_3-19-00-2](https://user-images.githubusercontent.com/1457929/63310499-431c0380-c2fb-11e9-9bfe-21252d8a491e.png)
